name: Build ARM64 with Native Runners

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: false
        default: 'latest'

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: |
        go mod download
        go mod tidy
        
    - name: Set up CGO environment for native build
      run: |
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "GOOS=linux" >> $GITHUB_ENV
        echo "GOARCH=arm64" >> $GITHUB_ENV
        
    - name: Build for Linux ARM64 (native)
      run: |
        VERSION="${{ github.event.inputs.version || 'latest' }}"
        BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        
        mkdir -p build
        go build -ldflags "-X main.version=$VERSION -X main.buildTime=$BUILD_TIME" -o "build/gateway-digiflazz-linux-arm64" ./cmd/server
        
    - name: Test binary
      run: |
        chmod +x build/gateway-digiflazz-linux-arm64
        ./build/gateway-digiflazz-linux-arm64 --help
        
    - name: Create archive
      run: |
        tar -czf "build/gateway-digiflazz-linux-arm64.tar.gz" -C build "gateway-digiflazz-linux-arm64"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gateway-digiflazz-linux-arm64
        path: |
          build/gateway-digiflazz-linux-arm64
          build/gateway-digiflazz-linux-arm64.tar.gz

  build-windows-arm64:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: |
        go mod download
        go mod tidy
        
    - name: Set up CGO environment
      run: |
        echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
        echo "GOOS=windows" >> $env:GITHUB_ENV
        echo "GOARCH=arm64" >> $env:GITHUB_ENV
        
    - name: Build for Windows ARM64
      run: |
        $version = "${{ github.event.inputs.version || 'latest' }}"
        $buildTime = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
        
        New-Item -ItemType Directory -Path "build" -Force
        go build -ldflags "-X main.version=$version -X main.buildTime=$buildTime" -o "build/gateway-digiflazz-windows-arm64.exe" ./cmd/server
        
    - name: Test binary
      run: |
        .\build\gateway-digiflazz-windows-arm64.exe --help
        
    - name: Create archive
      run: |
        Compress-Archive -Path "build\gateway-digiflazz-windows-arm64.exe" -DestinationPath "build\gateway-digiflazz-windows-arm64.zip"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gateway-digiflazz-windows-arm64
        path: |
          build/gateway-digiflazz-windows-arm64.exe
          build/gateway-digiflazz-windows-arm64.zip
