name: Build Windows with CGO

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: false
        default: 'latest'

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [amd64, 386]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: |
        go mod download
        go mod tidy
        
    - name: Set up CGO environment
      run: |
        echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
        echo "GOOS=windows" >> $env:GITHUB_ENV
        echo "GOARCH=${{ matrix.arch }}" >> $env:GITHUB_ENV
        
    - name: Build for Windows ${{ matrix.arch }}
      run: |
        $version = "${{ github.event.inputs.version || 'latest' }}"
        $buildTime = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
        
        go build -ldflags "-X main.version=$version -X main.buildTime=$buildTime" -o "build/gateway-digiflazz-windows-${{ matrix.arch }}.exe" ./cmd/server
        
    - name: Create build directory
      run: |
        if (!(Test-Path "build")) {
          New-Item -ItemType Directory -Path "build"
        }
        
    - name: Test binary
      run: |
        .\build\gateway-digiflazz-windows-${{ matrix.arch }}.exe --help
        
    - name: Create archive
      run: |
        Compress-Archive -Path "build\gateway-digiflazz-windows-${{ matrix.arch }}.exe" -DestinationPath "build\gateway-digiflazz-windows-${{ matrix.arch }}.zip"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gateway-digiflazz-windows-${{ matrix.arch }}
        path: |
          build/gateway-digiflazz-windows-${{ matrix.arch }}.exe
          build/gateway-digiflazz-windows-${{ matrix.arch }}.zip
          
    - name: Upload to Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/gateway-digiflazz-windows-${{ matrix.arch }}.zip
        draft: false
        prerelease: false
